-- CREATING A DATABASE
CREATE DATABASE school_db;

-- SWITCH TO A SPECIFIC DATABASE
use school_db;

-- CREATE A TABLE TO STORE OUR STUDENTS
CREATE TABLE tbl_student (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);